package cn.t.ytten.core.exception;

public class EventLoopTaskException extends RuntimeException {
    public EventLoopTaskException(Throwable cause) {
        super(cause);
    }
}
